"""baseline

Revision ID: 09aa0167dac4
Revises: 
Create Date: 2026-05-18 13:05:08.754792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aa0167dac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('is_pilot', sa.Boolean(), nullable=False),
    sa.Column('is_maintenance', sa.Boolean(), nullable=False),
    sa.Column('view_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=16), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('regime', sa.String(length=8), nullable=False),
    sa.Column('has_flight_counter', sa.Boolean(), nullable=False),
    sa.Column('flight_counter_offset', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('fuel_flow', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fuel_type', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('renter_user_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_user_id', sa.Integer(), nullable=True),
    sa.Column('viewer_user_id', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['renter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('medical_expiry', sa.Date(), nullable=True),
    sa.Column('sep_expiry', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tenant_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OWNER', 'PILOT', 'MAINTENANCE', 'VIEWER', 'STUDENT', 'INSTRUCTOR', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    op.create_table('user_all_aircraft_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('permissions_mask', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    op.create_table('user_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OWNER', 'PILOT', 'MAINTENANCE', 'VIEWER', 'STUDENT', 'INSTRUCTOR', name='role'), nullable=False),
    sa.Column('aircraft_ids', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('aircraft_booking_settings',
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('min_booking_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('max_booking_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aircraft_id')
    )
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('time_at_install', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('removed_at', sa.Date(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('departure_icao', sa.String(length=4), nullable=False),
    sa.Column('arrival_icao', sa.String(length=4), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('flight_time', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('nature_of_flight', sa.String(length=100), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=True),
    sa.Column('landing_count', sa.Integer(), nullable=True),
    sa.Column('flight_time_counter_start', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('flight_time_counter_end', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('engine_time_counter_start', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('engine_time_counter_end', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('flight_counter_photo', sa.String(length=255), nullable=True),
    sa.Column('engine_counter_photo', sa.String(length=255), nullable=True),
    sa.Column('fuel_event', sa.String(length=8), nullable=True),
    sa.Column('fuel_added_qty', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fuel_added_unit', sa.String(length=8), nullable=True),
    sa.Column('fuel_remaining_qty', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fuel_photo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('due_engine_hours', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('interval_hours', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('pilot_user_id', sa.Integer(), nullable=True),
    sa.Column('start_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='reservationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=8), nullable=False),
    sa.Column('access_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_tokens_token'), ['token'], unique=True)

    op.create_table('snags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reporter', sa.String(length=128), nullable=True),
    sa.Column('is_grounding', sa.Boolean(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_aircraft_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('permissions_mask', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'aircraft_id')
    )
    op.create_table('wb_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('empty_weight', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('empty_cg_arm', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('max_takeoff_weight', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('forward_cg_limit', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('aft_cg_limit', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('fuel_unit', sa.String(length=3), nullable=False),
    sa.Column('envelope_points', sa.JSON(), nullable=True),
    sa.Column('datum_note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aircraft_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('flight_entry_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flight_entry_id'], ['flight_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('flight_entry_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expense_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flight_entry_id'], ['flight_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.Date(), nullable=False),
    sa.Column('hobbs_at_service', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['maintenance_triggers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_logbook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('aircraft_type', sa.String(length=64), nullable=True),
    sa.Column('aircraft_registration', sa.String(length=16), nullable=True),
    sa.Column('departure_place', sa.String(length=64), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('arrival_place', sa.String(length=64), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('pic_name', sa.String(length=128), nullable=True),
    sa.Column('night_time', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('instrument_time', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('landings_day', sa.Integer(), nullable=True),
    sa.Column('landings_night', sa.Integer(), nullable=True),
    sa.Column('single_pilot_se', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('single_pilot_me', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('multi_pilot', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('function_pic', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('function_copilot', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('function_dual', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('function_instructor', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pilot_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wb_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('total_weight', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('loaded_cg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('is_in_envelope', sa.Boolean(), nullable=False),
    sa.Column('station_weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['wb_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wb_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('arm', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('max_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('is_fuel', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['wb_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_stations')
    op.drop_table('wb_entries')
    op.drop_table('pilot_logbook_entries')
    op.drop_table('maintenance_records')
    op.drop_table('flight_crew')
    op.drop_table('expenses')
    op.drop_table('documents')
    op.drop_table('wb_configs')
    op.drop_table('user_aircraft_access')
    op.drop_table('snags')
    with op.batch_alter_table('share_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_tokens_token'))

    op.drop_table('share_tokens')
    op.drop_table('reservations')
    op.drop_table('maintenance_triggers')
    op.drop_table('flight_entries')
    op.drop_table('components')
    op.drop_table('aircraft_booking_settings')
    op.drop_table('user_invitations')
    op.drop_table('user_all_aircraft_access')
    op.drop_table('tenant_users')
    op.drop_table('pilot_profiles')
    op.drop_table('demo_slots')
    op.drop_table('aircraft')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('backup_records')
    # ### end Alembic commands ###
