"""add_tenant_profile_and_invite_display_name

Revision ID: 119bc545da12
Revises: 09aa0167dac4
Create Date: 2026-05-19 05:54:54.561671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119bc545da12'
down_revision = '09aa0167dac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('operating_model', sa.Enum('SOLE_PILOT', 'SOLE_OPERATOR', 'SHARED_OWNERSHIP', 'FLIGHT_CLUB', 'FLIGHT_SCHOOL', name='operatingmodel'), nullable=True),
    sa.Column('planned_aircraft_count', sa.Integer(), nullable=True),
    sa.Column('allows_rental', sa.Boolean(), nullable=False),
    sa.Column('club_name', sa.String(length=128), nullable=True),
    sa.Column('school_name', sa.String(length=128), nullable=True),
    sa.Column('organisation_name', sa.String(length=128), nullable=True),
    sa.Column('setup_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    op.drop_table('tenant_profiles')
    # ### end Alembic commands ###
