"""widen token columns to 64 chars for secrets.token_urlsafe

Revision ID: ac0c46897a62
Revises: d5e6f7a8b9c0
Create Date: 2026-05-30 10:44:51.956137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0c46897a62'
down_revision = 'd5e6f7a8b9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
