[pytest]
testpaths = tests
pythonpath = app
addopts = -n auto --cov=app --cov-report=term-missing --cov-report=html:htmlcov --cov-report=xml:coverage.xml --cov-config=.coveragerc --cov-fail-under=100
